on: push

name: ci
jobs:
  ci:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Get Latest Release
        id: latest_version
        uses: ./
        with:
          owner: abatilo
          repo: release-info-action
